
[rendering]
	#Enable Tetratic Rescaling for Items in the players Hand.
	enableRescale = true

[technical]
	#Use Tetras AttackRange.
	tetraRange = true
	#Uses Tetras Quick Stat to Scale Upswing.
	quickIsUpsing = true
	#Set the stacks on Itemswitching - This is for older Worlds or config Changes, if you do not have old Items in your world you can turn this off
	fallBackApplyConfig = true

